In [ ]:
import numpy as np
import pandas as pd
import io 
import sklearn
from sklearn import preprocessing

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:

data=pd.read_csv(io.BytesIO(uploaded['DSL-StrongPasswordData.csv']))
print(data.head())
data=data.drop(["sessionIndex","rep"],axis=1)

  subject  sessionIndex  rep  ...  DD.l.Return  UD.l.Return  H.Return
0    s002             1    1  ...       0.3509       0.2171    0.0742
1    s002             1    2  ...       0.2756       0.1917    0.0747
2    s002             1    3  ...       0.2847       0.1762    0.0945
3    s002             1    4  ...       0.3232       0.2387    0.0813
4    s002             1    5  ...       0.2517       0.1614    0.0818

[5 rows x 34 columns]


# New Section

In [ ]:
le=preprocessing.LabelEncoder()
data['subject']=le.fit_transform(data['subject'])
print(data.head())


   subject  H.period  DD.period.t  ...  DD.l.Return  UD.l.Return  H.Return
0        0    0.1491       0.3979  ...       0.3509       0.2171    0.0742
1        0    0.1111       0.3451  ...       0.2756       0.1917    0.0747
2        0    0.1328       0.2072  ...       0.2847       0.1762    0.0945
3        0    0.1291       0.2515  ...       0.3232       0.2387    0.0813
4        0    0.1249       0.2317  ...       0.2517       0.1614    0.0818

[5 rows x 32 columns]


In [ ]:

print(data.head())
x=data.iloc[:,1:32].values
y=data.iloc[:,0:1].values
print(x[0])
print(y[0])

   subject  H.period  DD.period.t  ...  DD.l.Return  UD.l.Return  H.Return
0        0    0.1491       0.3979  ...       0.3509       0.2171    0.0742
1        0    0.1111       0.3451  ...       0.2756       0.1917    0.0747
2        0    0.1328       0.2072  ...       0.2847       0.1762    0.0945
3        0    0.1291       0.2515  ...       0.3232       0.2387    0.0813
4        0    0.1249       0.2317  ...       0.2517       0.1614    0.0818

[5 rows x 32 columns]
[0.1491 0.3979 0.2488 0.1069 0.1674 0.0605 0.1169 0.2212 0.1043 0.1417
 1.1885 1.0468 0.1146 1.6055 1.4909 0.1067 0.759  0.6523 0.1016 0.2136
 0.112  0.1349 0.1484 0.0135 0.0932 0.3515 0.2583 0.1338 0.3509 0.2171
 0.0742]
[0]


In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y.ravel(),test_size=0.1)

In [18]:
from sklearn.svm import SVC
clf=SVC(kernel='rbf')
clf.fit(xtrain,ytrain)
ypred=clf.predict(xtest)

print(xtest)

[[0.1056 0.1654 0.0598 ... 0.2461 0.1574 0.0985]
 [0.0723 0.258  0.1857 ... 0.3974 0.3327 0.0644]
 [0.1214 0.1316 0.0102 ... 0.2591 0.1197 0.1175]
 ...
 [0.1224 0.1637 0.0413 ... 0.2344 0.156  0.0781]
 [0.0486 0.5116 0.463  ... 0.6416 0.5996 0.0544]
 [0.0483 0.5445 0.4962 ... 0.336  0.242  0.0559]]


In [19]:
print(accuracy_score(ytest,ypred))

0.782843137254902
